// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Guilds         string
	RankRoles      string
	RegisterdRoles string
	Users          string
}{
	Guilds:         "guilds",
	RankRoles:      "rank_roles",
	RegisterdRoles: "registerd_roles",
	Users:          "users",
}
